### ISSUE TITLE
Use GH Actions to build against other OSs

### ISSUE THREAD

**Issue by mkolopanis** [cjordan/rust-erfa#1]
I'm looking at using this for erfa calculations in [uvdata-rust](https://github.com/mkolopanis/uvdata-rust.git) but want to be sure we can still support windows and mac os. I took some inspiration from [hdf5-rust](https://github.com/aldanor/hdf5-rust.git) when building my github workflow. 
You could build against macos and windows with something like the following. The real problem comes down to what if it doesn't work on non-unix :laughing: 
```yaml
jobs:
  build:
    name: test
        runs-on: ${{matrix.os}}-latest
        strategy:
          fail-fast: false
          matrix:
            include:
              - {os: ubuntu, rust: stable}
              - {os: windows, rust: stable}
              - {os: macos, rust: stable}
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
            with: {submodules: true}
          - name: Install Rust (${{matrix.rust}})
            uses: actions-rs/toolchain@v1
            with: {toolchain: '${{matrix.rust}}', profile: minimal, override: true}
          - name: Run tests
            run: |
              cargo test
              cd erfa-sys
              cargo test --features static
```
